### ISSUE TITLE
drake-visualizer cannot find Atlas meshes

### ISSUE THREAD

**Issue by oofrivia** [rcywongaa/humanoid#1]
how do you get drake-visualizer to find the Atlas meshes. 
I tryed add `export PYTHONPATH=/home/he/opensouece/humanoid:${PYTHONPATH}` 
or put the `robots/` folder at `opt/drake/share/drake/examples/`

and run the intalled drake-visualizer 
`./opt/drake/bin/drake-visualizer`
run 
`python3 HumanoidController.py`

and I got same error ,it is because drake-visualizer didn't find the meshed right?

> warning, cannot find file: robots/atlas/urdf/meshes/r_farm.obj
udp_read_packet -- select:: 被中断的系统调用
select() interrupted
udp_read_packet -- select:: 被中断的系统调用
select() interrupted
udp_read_packet -- select:: 被中断的系统调用
select() interrupted
udp_read_packet -- select:: 被中断的系统调用
select() interrupted
Traceback (most recent call last):
  File "/opt/drake/lib/python3.8/site-packages/director/lcmUtils.py", line 119, in handleMessage
    callback(msg)
  File "/opt/drake/lib/python3.8/site-packages/director/drakevisualizer.py", line 335, in onViewerLoadRobot
    self.addLinksFromLCM(msg)
  File "/opt/drake/lib/python3.8/site-packages/director/drakevisualizer.py", line 359, in addLinksFromLCM
    self.addLink(Link(link), link.robot_num, link.name)
  File "/opt/drake/lib/python3.8/site-packages/director/drakevisualizer.py", line 284, in __init__
    self.geometry.extend(Geometry.createGeometry(link.name + ' geometry data', g))
  File "/opt/drake/lib/python3.8/site-packages/director/drakevisualizer.py", line 257, in createGeometry
    polyDataList, visInfo = Geometry.createPolyDataFromFiles(geom)
ValueError: not enough values to unpack (expected 2, got 0)
Error locating link name: plant::atlas::r_ufarm
Error locating link name: plant::atlas::r_hand_force_torque
Error locating link name: plant::atlas::r_lglut
Error locating link name: plant::atlas::l_ufarm
Error locating link name: plant::atlas::l_uglut
Error locating link name: plant::atlas::l_hand_force_torque
Error locating link name: plant::atlas::r_lfarm
Error locating link name: plant::atlas::l_larm
Error locating link name: plant::atlas::utorso
Error locating link name: plant::atlas::r_uleg
...

**Comment by oofrivia** [comment]
these error message above is given by drake-visualizer.
the `python3 HumanoidController.py` gives quite normal prints

> Formulate time: 0.0388033390045166s
Solve time: 0.01068258285522461s
Cost: 0.009835786765234578
Formulate time: 0.0392765998840332s
Solve time: 0.01069331169128418s
Cost: 0.009835446889647558
Formulate time: 0.039763450622558594s
Solve time: 0.010625839233398438s
Cost: 0.009835100456447726
Formulate time: 0.03856039047241211s
Solve time: 0.010625362396240234s
Cost: 0.009834747470374895
Formulate time: 0.03860330581665039s
Solve time: 0.010636091232299805s
Cost: 0.009834387935969168
Formulate time: 0.03917288780212402s
Solve time: 0.010590076446533203s
Cost: 0.00983402185757585

**Comment by oofrivia** [comment]
@rcywongaa in case you didn't get notice

**Comment by rcywongaa** [comment]
Hi @zisang , sorry for the delay.  Welcome to my repo and thanks for opening my first issue!  I'm able to reproduce it (not sure why it didn't happen before) and am looking into it.  Do let me know if you figure anything out as well.

**Comment by zisang** [comment]
hi @rcywongaa , I am excited to find your implements.

**Comment by oofrivia** [comment]
Hi @rcywongaa , I am excited to find your implements.
You write in your readme `Other tools/Visualization` is director `https://github.com/RobotLocomotion/director`. What visualization tools do you use before? I am using a binary installation of drake in ubuntu 20.04. 
Your are using models in `humanoid/robots/` right? Do you think Is it necessary to let `/opt/drake/bin/drake-visualizer` find where `humanoid/robots/` is.
I also tried to replace `/opt/drake/share/drake/examples/atlas` with `humanoid/robots/atlas`, but it didn't work.

I also runned Planner.py, and it works perfectly.

**Comment by rcywongaa** [comment]
I've changed `HumanoidController.py` to use meshcat visualizer instead.  The benefit is that meshcat visualizer supports recording and playback at the correct speeds so no need to manually record the frames to create the video.

I asked a question about when to use which visualizer [here](https://stackoverflow.com/questions/68530042/when-to-use-drake-visualizer-vs-meshcat-visualizer/68530253#68530253) of which Prof. Russ Tedrake graciously answered.  The key point being they intend to eventually move away from `drake-visualizer`.

**Comment by rcywongaa** [comment]
The Random Notes section is just my scratchpad for jotting down random stuff that I find useful... might be a good idea to move it out of the README to avoid confusion

**Comment by oofrivia** [comment]
I runned the meshcat visualizer version, and it works fine. Thanks!!

**Comment by rcywongaa** [comment]
Great!
